[package]
name = "day20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree_list = { path = "tree_list" }

[[bin]]
name = "day20"
path = "main.rs"
